---
- name: install rbenv
  homebrew:
    name: rbenv
    state: present

- name: initialize rbenv
  shell: rbenv init
  ignore_errors: true

- name: install ruby
  shell: rbenv install 2.3.1

- name: set global ruby version
  shell: rbenv global 2.3.1
